In [1]:
import pandas as pd
import numpy as np

In [12]:
data = {
    "title": ["Toy Story (1995)", "Fortunes", 
              "Silences of the Palace (Saimt el Qusur) (1994)",
              "The Thing (2011)"]
}
df = pd.DataFrame(data)

### Moving parts of the title in a new column

In [14]:
df["year"] = df["title"].str.extract(r"\((\d{4})\)$")
df

                                            title  year
0                                Toy Story (1995)  1995
1                                        Fortunes   NaN
2  Silences of the Palace (Saimt el Qusur) (1994)  1994
3                                The Thing (2011)  2011

### Remove part of the string
The pattern needed: "\\(\d{4}\)$"
Breaking it down:

\( — a literal opening parenthesis (the backslash means "this is a real bracket, not a regex symbol")
\d{4} — exactly 4 digits
\) — a literal closing parenthesis
$ — end of the string

In [15]:
df["title"]= df["title"].str.replace(r"\(\d{4}\)$","", regex=True).str.strip()

df.head()

                                     title  year
0                                Toy Story  1995
1                                 Fortunes   NaN
2  Silences of the Palace (Saimt el Qusur)  1994
3                                The Thing  2011